export const SET_SYSTEM_AUTH = 'SET_SYSTEM_AUTH';

export const SET_CURRENT_PATH = 'SET_CURRENT_PATH';
export const SET_DIRECTORIES = 'SET_DIRECTORIES';
export const SET_INSTALLED_SOFTWARES = 'SET_INSTALLED_SOFTWARES';

export const SET_SYSTEM_CMD = 'SET_SYSTEM_CMD';

export const SET_DEVICE_HARDWARES = 'SET_DEVICE_HARDWARES';
export const SET_CPU_REGISTERS = 'SET_CPU_REGISTERS';
export const SET_MEMORY_REGISTERS = 'SET_MEMORY_REGISTERS';

export const SET_DATE_TIME = 'SET_DATE_TIME';