export const SET_SYSTEM_AUTH = 'SET_SYSTEM_AUTH';

export const SET_CURRENT_PATH = 'SET_CURRENT_PATH';
export const SET_DIRECTORIES = 'SET_DIRECTORIES';
export const SET_DEFAULT_DIRECTORIES = 'SET_DEFAULT_DIRECTORIES';
export const SET_INSTALLED_SOFTWARES = 'SET_INSTALLED_SOFTWARES';
export const SET_COMMAND_LINE = 'SET_COMMAND_LINE';
export const SET_DEFAULT_COMMAND_LINE = 'SET_DEFAULT_COMMAND_LINE';
export const SET_SHORTCUTS_LIST = 'SET_SHORTCUTS_LIST';
export const SET_DEFAULT_SHORTCUTS_LIST = 'SET_DEFAULT_SHORTCUTS_LIST';

export const SET_SYSTEM_CMD = 'SET_SYSTEM_CMD';
export const SET_SYSTEM_CMD_DEFAULT = 'SET_SYSTEM_CMD_DEFAULT';

export const SET_DEVICE_HARDWARES = 'SET_DEVICE_HARDWARES';
export const SET_CPU_REGISTERS = 'SET_CPU_REGISTERS';
export const SET_MEMORY_REGISTERS = 'SET_MEMORY_REGISTERS';

export const SET_DATE_TIME = 'SET_DATE_TIME';

export const SET_BATTERY_STATUS = "SET_BATTERY_STATUS";

export const SET_CONFIRM_EXIT_MODAL_TOGGLE = 'SET_CONFIRM_EXIT_MODAL_TOGGLE';
export const SET_CONFIRM_EXIT_MODAL_TOGGLE_DELAY = 'SET_CONFIRM_EXIT_MODAL_TOGGLE_DELAY';